//
//  Constants.swift
//  TimeIndicatorPOC
//
//  Created by Sweda Thiyagarajan on 19/05/2022.
//

struct ChannelList {
    static let SUNTV = "Sun TV"
    static let VIJAYTV = "Vijay TV"
    static let RAJMOVIES = "Raj movies"
    static let JAYATV = "Jaya TV"
    static let ZEETAMIL = "Zee Tamil"
    static let POLIMER = "Polimer"
    static let PUTHIYATHALAIMURAI = "Puthiyathalaimurai"
    static let NEWS7 = "News 7"
    static let NEWS18 = "News 18"
    static let SUNNEWS = "Sun news"
    static let JAYANEWS = "Jaya news"
    static let MAALAIMURASU = "Malai murasu"
    static let SUNMUSIC = "Sun music"
    static let VIJAYMUSIC = "Vijay music"
    static let JAYAMAX = "Jaya max"
    static let SUNMOVIES = "Sun movies"
    static let VIJAYSUPER = "Vijay super"
    static let ZEETHIRAI = "Zee Thirai"
    static let RAJMUSIC = "Raj music"
    static let RAJNEWS = "Raj news"
}

struct ShowTime {
    static let FROM = "from"
    static let TO = "to"
}

struct Show {
    static let NAME = "name"
}

struct ShowList {
    static let SUNTV = [[Show.NAME: "Paadal", ShowTime.FROM: "00:00", ShowTime.TO: "00:30"],
                            [Show.NAME: "Music", ShowTime.FROM: "00:30", ShowTime.TO: "01:00"],
                            [Show.NAME: "Old songs", ShowTime.FROM: "01:30", ShowTime.TO: "02:00"]]/*,
                            [Show.NAME: "Neengal ketavai", ShowTime.FROM: "02:00", ShowTime.TO: "02:30"],
                            [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "02:30", ShowTime.TO: "03:00"],
                            [Show.NAME: "Classics", ShowTime.FROM: "03:00", ShowTime.TO: "03:30"],
                            [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "03:30", ShowTime.TO: "04:00"],
                            [Show.NAME: "Devotional songs", ShowTime.FROM: "04:00", ShowTime.TO: "04:30"],
                            [Show.NAME: "Karnatic songs", ShowTime.FROM: "04:30", ShowTime.TO: "05:00"],
                            [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                            [Show.NAME: "News", ShowTime.FROM: "06:00", ShowTime.TO: "06:30"],
                            [Show.NAME: "Movie review", ShowTime.FROM: "06:30", ShowTime.TO: "07:00"],
                            [Show.NAME: "80s reminder", ShowTime.FROM: "07:00", ShowTime.TO: "07:30"],
                            [Show.NAME: "Non stop songs", ShowTime.FROM: "07:30", ShowTime.TO: "08:30"],
                            [Show.NAME: "Movie", ShowTime.FROM: "07:30", ShowTime.TO: "10:30"],
                            [Show.NAME: "Debate", ShowTime.FROM: "10:30", ShowTime.TO: "12:00"],
                            [Show.NAME: "Trailer show", ShowTime.FROM: "12:00", ShowTime.TO: "12:30"],
                            [Show.NAME: "Paadal", ShowTime.FROM: "12:30", ShowTime.TO: "13:00"],
                            [Show.NAME: "Music", ShowTime.FROM: "13:00", ShowTime.TO: "13:30"],
                            [Show.NAME: "Old songs", ShowTime.FROM: "13:30", ShowTime.TO: "14:00"],
                            [Show.NAME: "Neengal ketavai", ShowTime.FROM: "14:00", ShowTime.TO: "14:30"],
                            [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "14:30", ShowTime.TO: "15:00"],
                            [Show.NAME: "Classics", ShowTime.FROM: "15:00", ShowTime.TO: "15:30"],
                            [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "15:30", ShowTime.TO: "16:00"],
                            [Show.NAME: "Devotional songs", ShowTime.FROM: "16:00", ShowTime.TO: "16:30"],
                            [Show.NAME: "Karnatic songs", ShowTime.FROM: "16:30", ShowTime.TO: "17:00"],
                            [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                            [Show.NAME: "News", ShowTime.FROM: "18:00", ShowTime.TO: "18:30"],
                            [Show.NAME: "Movie review", ShowTime.FROM: "18:30", ShowTime.TO: "19:00"],
                            [Show.NAME: "80s reminder", ShowTime.FROM: "19:00", ShowTime.TO: "19:30"],
                            [Show.NAME: "Non stop songs", ShowTime.FROM: "19:30", ShowTime.TO: "20:30"],
                            [Show.NAME: "Movie", ShowTime.FROM: "20:30", ShowTime.TO: "23:30"],
                            [Show.NAME: "Debate", ShowTime.FROM: "23:30", ShowTime.TO: "00:00"]]*/

    static let VIJAYTV = [[Show.NAME: "Paadal", ShowTime.FROM: "00:00", ShowTime.TO: "00:30"],
                            [Show.NAME: "Music", ShowTime.FROM: "00:30", ShowTime.TO: "01:00"],
                            [Show.NAME: "Old songs", ShowTime.FROM: "01:30", ShowTime.TO: "02:00"],
                            [Show.NAME: "Neengal ketavai", ShowTime.FROM: "02:00", ShowTime.TO: "02:30"],
                            [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "02:30", ShowTime.TO: "03:00"],
                            [Show.NAME: "Classics", ShowTime.FROM: "03:00", ShowTime.TO: "03:30"],
                            [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "03:30", ShowTime.TO: "04:00"],
                            [Show.NAME: "Devotional songs", ShowTime.FROM: "04:00", ShowTime.TO: "04:30"],
                            [Show.NAME: "Karnatic songs", ShowTime.FROM: "04:30", ShowTime.TO: "05:00"],
                            [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                            [Show.NAME: "Classical movie", ShowTime.FROM: "06:00", ShowTime.TO: "09:00"],
                            [Show.NAME: "Movie review", ShowTime.FROM: "09:30", ShowTime.TO: "10:00"],
                            [Show.NAME: "80s reminder", ShowTime.FROM: "10:00", ShowTime.TO: "10:30"],
                            [Show.NAME: "Non stop songs", ShowTime.FROM: "10:30", ShowTime.TO: "11:30"],
                            [Show.NAME: "Movie", ShowTime.FROM: "07:30", ShowTime.TO: "10:30"],
                            [Show.NAME: "Debate", ShowTime.FROM: "10:30", ShowTime.TO: "12:00"],
                            [Show.NAME: "Trailer show", ShowTime.FROM: "12:00", ShowTime.TO: "12:30"],
                            [Show.NAME: "Paadal", ShowTime.FROM: "12:30", ShowTime.TO: "13:00"],
                            [Show.NAME: "Music", ShowTime.FROM: "13:00", ShowTime.TO: "13:30"],
                            [Show.NAME: "Old songs", ShowTime.FROM: "13:30", ShowTime.TO: "14:00"],
                            [Show.NAME: "Neengal ketavai", ShowTime.FROM: "14:00", ShowTime.TO: "14:30"],
                            [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "14:30", ShowTime.TO: "15:00"],
                            [Show.NAME: "Classics", ShowTime.FROM: "15:00", ShowTime.TO: "15:30"],
                            [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "15:30", ShowTime.TO: "16:00"],
                            [Show.NAME: "Devotional songs", ShowTime.FROM: "16:00", ShowTime.TO: "16:30"],
                            [Show.NAME: "Karnatic songs", ShowTime.FROM: "16:30", ShowTime.TO: "17:00"],
                            [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                            [Show.NAME: "Classical movie", ShowTime.FROM: "18:00", ShowTime.TO: "21:00"],
                            [Show.NAME: "Movie review", ShowTime.FROM: "21:00", ShowTime.TO: "21:30"],
                            [Show.NAME: "80s reminder", ShowTime.FROM: "21:30", ShowTime.TO: "22:00"],
                            [Show.NAME: "Non stop songs", ShowTime.FROM: "22:00", ShowTime.TO: "23:30"],
                            [Show.NAME: "Movie", ShowTime.FROM: "23:30", ShowTime.TO: "00:00"]]
    
    static let RAJMOVIES = [[Show.NAME: "movie 1", ShowTime.FROM: "00:00", ShowTime.TO: "03:00"],
                            [Show.NAME: "movie 2", ShowTime.FROM: "03:00", ShowTime.TO: "06:00"],
                            [Show.NAME: "movie 3", ShowTime.FROM: "06:00", ShowTime.TO: "09:00"],
                            [Show.NAME: "movie 4", ShowTime.FROM: "09:00", ShowTime.TO: "12:00"],
                            [Show.NAME: "movie 5", ShowTime.FROM: "12:00", ShowTime.TO: "15:00"],
                            [Show.NAME: "movie 6", ShowTime.FROM: "15:00", ShowTime.TO: "18:00"],
                            [Show.NAME: "movie 7", ShowTime.FROM: "18:00", ShowTime.TO: "21:00"],
                            [Show.NAME: "movie 8", ShowTime.FROM: "21:00", ShowTime.TO: "00:00"]]
    
    static let SUNNEWS = [[Show.NAME: "Early morning news", ShowTime.FROM: "00:00", ShowTime.TO: "01:00"],
                        [Show.NAME: "Sports news", ShowTime.FROM: "01:00", ShowTime.TO: "02:00"],
                        [Show.NAME: "World politics", ShowTime.FROM: "02:00", ShowTime.TO: "03:00"],
                        [Show.NAME: "Wether prediction for globe", ShowTime.FROM: "03:00", ShowTime.TO: "04:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "04:00", ShowTime.TO: "05:00"],
                        [Show.NAME: "International updates", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "06:00", ShowTime.TO: "07:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "07:00", ShowTime.TO: "08:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "08:00", ShowTime.TO: "09:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "10:00", ShowTime.TO: "11:00"],
                        [Show.NAME: "Science to discuss", ShowTime.FROM: "11:00", ShowTime.TO: "12:00"],
                        [Show.NAME: "Animals around us", ShowTime.FROM: "12:00", ShowTime.TO: "13:00"],
                        [Show.NAME: "Water resources and management", ShowTime.FROM: "13:00", ShowTime.TO: "14:00"],
                        [Show.NAME: "Kollywood Box office", ShowTime.FROM: "14:00", ShowTime.TO: "15:00"],
                        [Show.NAME: "Cinema updates", ShowTime.FROM: "15:00", ShowTime.TO: "16:00"],
                        [Show.NAME: "Evening upodates" , ShowTime.FROM: "16:00", ShowTime.TO: "17:00"],
                        [Show.NAME: "Global climate", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "18:00", ShowTime.TO: "19:00"],
                        [Show.NAME: "Hot news", ShowTime.FROM: "19:00", ShowTime.TO: "20:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "20:00", ShowTime.TO: "21:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "21:00", ShowTime.TO: "22:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "22:00", ShowTime.TO: "23:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "23:00", ShowTime.TO: "00:00"]]

    
    static let JAYATV = [[Show.NAME: "Paadal", ShowTime.FROM: "00:00", ShowTime.TO: "00:30"],
                         [Show.NAME: "Music", ShowTime.FROM: "00:30", ShowTime.TO: "01:00"],
                         [Show.NAME: "Old songs", ShowTime.FROM: "01:30", ShowTime.TO: "02:00"],
                         [Show.NAME: "Neengal ketavai", ShowTime.FROM: "02:00", ShowTime.TO: "02:30"],
                         [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "02:30", ShowTime.TO: "03:00"],
                         [Show.NAME: "Classics", ShowTime.FROM: "03:00", ShowTime.TO: "03:30"],
                         [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "03:30", ShowTime.TO: "04:00"],
                         [Show.NAME: "Devotional songs", ShowTime.FROM: "04:00", ShowTime.TO: "04:30"],
                         [Show.NAME: "Karnatic songs", ShowTime.FROM: "04:30", ShowTime.TO: "05:00"],
                         [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                         [Show.NAME: "Classical movie", ShowTime.FROM: "06:00", ShowTime.TO: "09:00"],
                         [Show.NAME: "Movie review", ShowTime.FROM: "09:30", ShowTime.TO: "10:00"],
                         [Show.NAME: "80s reminder", ShowTime.FROM: "10:00", ShowTime.TO: "10:30"],
                         [Show.NAME: "Non stop songs", ShowTime.FROM: "10:30", ShowTime.TO: "11:30"],
                         [Show.NAME: "Movie", ShowTime.FROM: "07:30", ShowTime.TO: "10:30"],
                         [Show.NAME: "Debate", ShowTime.FROM: "10:30", ShowTime.TO: "12:00"],
                         [Show.NAME: "Trailer show", ShowTime.FROM: "12:00", ShowTime.TO: "12:30"],
                         [Show.NAME: "Paadal", ShowTime.FROM: "12:30", ShowTime.TO: "13:00"],
                         [Show.NAME: "Music", ShowTime.FROM: "13:00", ShowTime.TO: "13:30"],
                         [Show.NAME: "Old songs", ShowTime.FROM: "13:30", ShowTime.TO: "14:00"],
                         [Show.NAME: "Neengal ketavai", ShowTime.FROM: "14:00", ShowTime.TO: "14:30"],
                         [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "14:30", ShowTime.TO: "15:00"],
                         [Show.NAME: "Classics", ShowTime.FROM: "15:00", ShowTime.TO: "15:30"],
                         [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "15:30", ShowTime.TO: "16:00"],
                         [Show.NAME: "Devotional songs", ShowTime.FROM: "16:00", ShowTime.TO: "16:30"],
                         [Show.NAME: "Karnatic songs", ShowTime.FROM: "16:30", ShowTime.TO: "17:00"],
                         [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                         [Show.NAME: "Classical movie", ShowTime.FROM: "18:00", ShowTime.TO: "21:00"],
                         [Show.NAME: "Movie review", ShowTime.FROM: "21:00", ShowTime.TO: "21:30"],
                         [Show.NAME: "80s reminder", ShowTime.FROM: "21:30", ShowTime.TO: "22:00"],
                         [Show.NAME: "Non stop songs", ShowTime.FROM: "22:00", ShowTime.TO: "23:30"],
                         [Show.NAME: "Movie", ShowTime.FROM: "23:30", ShowTime.TO: "00:00"]]
    
    static let ZEETAMIL = [[Show.NAME: "Paadal", ShowTime.FROM: "00:00", ShowTime.TO: "00:30"],
                           [Show.NAME: "Music", ShowTime.FROM: "00:30", ShowTime.TO: "01:00"],
                           [Show.NAME: "Old songs", ShowTime.FROM: "01:30", ShowTime.TO: "02:00"],
                           [Show.NAME: "Neengal ketavai", ShowTime.FROM: "02:00", ShowTime.TO: "02:30"],
                           [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "02:30", ShowTime.TO: "03:00"],
                           [Show.NAME: "Classics", ShowTime.FROM: "03:00", ShowTime.TO: "03:30"],
                           [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "03:30", ShowTime.TO: "04:00"],
                           [Show.NAME: "Devotional songs", ShowTime.FROM: "04:00", ShowTime.TO: "04:30"],
                           [Show.NAME: "Karnatic songs", ShowTime.FROM: "04:30", ShowTime.TO: "05:00"],
                           [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                           [Show.NAME: "Classical movie", ShowTime.FROM: "06:00", ShowTime.TO: "09:00"],
                           [Show.NAME: "Movie review", ShowTime.FROM: "09:30", ShowTime.TO: "10:00"],
                           [Show.NAME: "80s reminder", ShowTime.FROM: "10:00", ShowTime.TO: "10:30"],
                           [Show.NAME: "Non stop songs", ShowTime.FROM: "10:30", ShowTime.TO: "11:30"],
                           [Show.NAME: "Movie", ShowTime.FROM: "07:30", ShowTime.TO: "10:30"],
                           [Show.NAME: "Debate", ShowTime.FROM: "10:30", ShowTime.TO: "12:00"],
                           [Show.NAME: "Trailer show", ShowTime.FROM: "12:00", ShowTime.TO: "12:30"],
                           [Show.NAME: "Paadal", ShowTime.FROM: "12:30", ShowTime.TO: "13:00"],
                           [Show.NAME: "Music", ShowTime.FROM: "13:00", ShowTime.TO: "13:30"],
                           [Show.NAME: "Old songs", ShowTime.FROM: "13:30", ShowTime.TO: "14:00"],
                           [Show.NAME: "Neengal ketavai", ShowTime.FROM: "14:00", ShowTime.TO: "14:30"],
                           [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "14:30", ShowTime.TO: "15:00"],
                           [Show.NAME: "Classics", ShowTime.FROM: "15:00", ShowTime.TO: "15:30"],
                           [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "15:30", ShowTime.TO: "16:00"],
                           [Show.NAME: "Devotional songs", ShowTime.FROM: "16:00", ShowTime.TO: "16:30"],
                           [Show.NAME: "Karnatic songs", ShowTime.FROM: "16:30", ShowTime.TO: "17:00"],
                           [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                           [Show.NAME: "Classical movie", ShowTime.FROM: "18:00", ShowTime.TO: "21:00"],
                           [Show.NAME: "Movie review", ShowTime.FROM: "21:00", ShowTime.TO: "21:30"],
                           [Show.NAME: "80s reminder", ShowTime.FROM: "21:30", ShowTime.TO: "22:00"],
                           [Show.NAME: "Non stop songs", ShowTime.FROM: "22:00", ShowTime.TO: "23:30"],
                           [Show.NAME: "Movie", ShowTime.FROM: "23:30", ShowTime.TO: "00:00"]]
    
    static let POLIMER = [[Show.NAME: "Paadal", ShowTime.FROM: "00:00", ShowTime.TO: "00:30"],
                          [Show.NAME: "Music", ShowTime.FROM: "00:30", ShowTime.TO: "01:00"],
                          [Show.NAME: "Old songs", ShowTime.FROM: "01:30", ShowTime.TO: "02:00"],
                          [Show.NAME: "Neengal ketavai", ShowTime.FROM: "02:00", ShowTime.TO: "02:30"],
                          [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "02:30", ShowTime.TO: "03:00"],
                          [Show.NAME: "Classics", ShowTime.FROM: "03:00", ShowTime.TO: "03:30"],
                          [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "03:30", ShowTime.TO: "04:00"],
                          [Show.NAME: "Devotional songs", ShowTime.FROM: "04:00", ShowTime.TO: "04:30"],
                          [Show.NAME: "Karnatic songs", ShowTime.FROM: "04:30", ShowTime.TO: "05:00"],
                          [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                          [Show.NAME: "Classical movie", ShowTime.FROM: "06:00", ShowTime.TO: "09:00"],
                          [Show.NAME: "Movie review", ShowTime.FROM: "09:30", ShowTime.TO: "10:00"],
                          [Show.NAME: "80s reminder", ShowTime.FROM: "10:00", ShowTime.TO: "10:30"],
                          [Show.NAME: "Non stop songs", ShowTime.FROM: "10:30", ShowTime.TO: "11:30"],
                          [Show.NAME: "Movie", ShowTime.FROM: "07:30", ShowTime.TO: "10:30"],
                          [Show.NAME: "Debate", ShowTime.FROM: "10:30", ShowTime.TO: "12:00"],
                          [Show.NAME: "Trailer show", ShowTime.FROM: "12:00", ShowTime.TO: "12:30"],
                          [Show.NAME: "Paadal", ShowTime.FROM: "12:30", ShowTime.TO: "13:00"],
                          [Show.NAME: "Music", ShowTime.FROM: "13:00", ShowTime.TO: "13:30"],
                          [Show.NAME: "Old songs", ShowTime.FROM: "13:30", ShowTime.TO: "14:00"],
                          [Show.NAME: "Neengal ketavai", ShowTime.FROM: "14:00", ShowTime.TO: "14:30"],
                          [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "14:30", ShowTime.TO: "15:00"],
                          [Show.NAME: "Classics", ShowTime.FROM: "15:00", ShowTime.TO: "15:30"],
                          [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "15:30", ShowTime.TO: "16:00"],
                          [Show.NAME: "Devotional songs", ShowTime.FROM: "16:00", ShowTime.TO: "16:30"],
                          [Show.NAME: "Karnatic songs", ShowTime.FROM: "16:30", ShowTime.TO: "17:00"],
                          [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                          [Show.NAME: "Classical movie", ShowTime.FROM: "18:00", ShowTime.TO: "21:00"],
                          [Show.NAME: "Movie review", ShowTime.FROM: "21:00", ShowTime.TO: "21:30"],
                          [Show.NAME: "80s reminder", ShowTime.FROM: "21:30", ShowTime.TO: "22:00"],
                          [Show.NAME: "Non stop songs", ShowTime.FROM: "22:00", ShowTime.TO: "23:30"],
                          [Show.NAME: "Movie", ShowTime.FROM: "23:30", ShowTime.TO: "00:00"]]
    
    static let JAYANEWS = [[Show.NAME: "Early morning news", ShowTime.FROM: "00:00", ShowTime.TO: "01:00"],
                        [Show.NAME: "Sports news", ShowTime.FROM: "01:00", ShowTime.TO: "02:00"],
                        [Show.NAME: "World politics", ShowTime.FROM: "02:00", ShowTime.TO: "03:00"],
                        [Show.NAME: "Wether prediction for globe", ShowTime.FROM: "03:00", ShowTime.TO: "04:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "04:00", ShowTime.TO: "05:00"],
                        [Show.NAME: "International updates", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "06:00", ShowTime.TO: "07:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "07:00", ShowTime.TO: "08:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "08:00", ShowTime.TO: "09:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "10:00", ShowTime.TO: "11:00"],
                        [Show.NAME: "Science to discuss", ShowTime.FROM: "11:00", ShowTime.TO: "12:00"],
                        [Show.NAME: "Animals around us", ShowTime.FROM: "12:00", ShowTime.TO: "13:00"],
                        [Show.NAME: "Water resources and management", ShowTime.FROM: "13:00", ShowTime.TO: "14:00"],
                        [Show.NAME: "Kollywood Box office", ShowTime.FROM: "14:00", ShowTime.TO: "15:00"],
                        [Show.NAME: "Cinema updates", ShowTime.FROM: "15:00", ShowTime.TO: "16:00"],
                        [Show.NAME: "Evening upodates" , ShowTime.FROM: "16:00", ShowTime.TO: "17:00"],
                        [Show.NAME: "Global climate", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "18:00", ShowTime.TO: "19:00"],
                        [Show.NAME: "Hot news", ShowTime.FROM: "19:00", ShowTime.TO: "20:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "20:00", ShowTime.TO: "21:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "21:00", ShowTime.TO: "22:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "22:00", ShowTime.TO: "23:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "23:00", ShowTime.TO: "00:00"]]

    
    static let PUTHIYATHALAIMURAI = [[Show.NAME: "Paadal", ShowTime.FROM: "00:00", ShowTime.TO: "00:30"],
                                     [Show.NAME: "Music", ShowTime.FROM: "00:30", ShowTime.TO: "01:00"],
                                     [Show.NAME: "Old songs", ShowTime.FROM: "01:30", ShowTime.TO: "02:00"],
                                     [Show.NAME: "Neengal ketavai", ShowTime.FROM: "02:00", ShowTime.TO: "02:30"],
                                     [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "02:30", ShowTime.TO: "03:00"],
                                     [Show.NAME: "Classics", ShowTime.FROM: "03:00", ShowTime.TO: "03:30"],
                                     [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "03:30", ShowTime.TO: "04:00"],
                                     [Show.NAME: "Devotional songs", ShowTime.FROM: "04:00", ShowTime.TO: "04:30"],
                                     [Show.NAME: "Karnatic songs", ShowTime.FROM: "04:30", ShowTime.TO: "05:00"],
                                     [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                                     [Show.NAME: "Classical movie", ShowTime.FROM: "06:00", ShowTime.TO: "09:00"],
                                     [Show.NAME: "Movie review", ShowTime.FROM: "09:30", ShowTime.TO: "10:00"],
                                     [Show.NAME: "80s reminder", ShowTime.FROM: "10:00", ShowTime.TO: "10:30"],
                                     [Show.NAME: "Non stop songs", ShowTime.FROM: "10:30", ShowTime.TO: "11:30"],
                                     [Show.NAME: "Movie", ShowTime.FROM: "07:30", ShowTime.TO: "10:30"],
                                     [Show.NAME: "Debate", ShowTime.FROM: "10:30", ShowTime.TO: "12:00"],
                                     [Show.NAME: "Trailer show", ShowTime.FROM: "12:00", ShowTime.TO: "12:30"],
                                     [Show.NAME: "Paadal", ShowTime.FROM: "12:30", ShowTime.TO: "13:00"],
                                     [Show.NAME: "Music", ShowTime.FROM: "13:00", ShowTime.TO: "13:30"],
                                     [Show.NAME: "Old songs", ShowTime.FROM: "13:30", ShowTime.TO: "14:00"],
                                     [Show.NAME: "Neengal ketavai", ShowTime.FROM: "14:00", ShowTime.TO: "14:30"],
                                     [Show.NAME: "Nenjil ninravai", ShowTime.FROM: "14:30", ShowTime.TO: "15:00"],
                                     [Show.NAME: "Classics", ShowTime.FROM: "15:00", ShowTime.TO: "15:30"],
                                     [Show.NAME: "Ilayarajan hits", ShowTime.FROM: "15:30", ShowTime.TO: "16:00"],
                                     [Show.NAME: "Devotional songs", ShowTime.FROM: "16:00", ShowTime.TO: "16:30"],
                                     [Show.NAME: "Karnatic songs", ShowTime.FROM: "16:30", ShowTime.TO: "17:00"],
                                     [Show.NAME: "Vanakam thamizha", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                                     [Show.NAME: "Classical movie", ShowTime.FROM: "18:00", ShowTime.TO: "21:00"],
                                     [Show.NAME: "Movie review", ShowTime.FROM: "21:00", ShowTime.TO: "21:30"],
                                     [Show.NAME: "80s reminder", ShowTime.FROM: "21:30", ShowTime.TO: "22:00"],
                                     [Show.NAME: "Non stop songs", ShowTime.FROM: "22:00", ShowTime.TO: "23:30"],
                                     [Show.NAME: "Movie", ShowTime.FROM: "23:30", ShowTime.TO: "00:00"]]
    
    static let NEWS7 = [[Show.NAME: "Early morning news", ShowTime.FROM: "00:00", ShowTime.TO: "01:00"],
                        [Show.NAME: "Sports news", ShowTime.FROM: "01:00", ShowTime.TO: "02:00"],
                        [Show.NAME: "World politics", ShowTime.FROM: "02:00", ShowTime.TO: "03:00"],
                        [Show.NAME: "Wether prediction for globe", ShowTime.FROM: "03:00", ShowTime.TO: "04:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "04:00", ShowTime.TO: "05:00"],
                        [Show.NAME: "International updates", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "06:00", ShowTime.TO: "07:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "07:00", ShowTime.TO: "08:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "08:00", ShowTime.TO: "09:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "10:00", ShowTime.TO: "11:00"],
                        [Show.NAME: "Science to discuss", ShowTime.FROM: "11:00", ShowTime.TO: "12:00"],
                        [Show.NAME: "Animals around us", ShowTime.FROM: "12:00", ShowTime.TO: "13:00"],
                        [Show.NAME: "Water resources and management", ShowTime.FROM: "13:00", ShowTime.TO: "14:00"],
                        [Show.NAME: "Kollywood Box office", ShowTime.FROM: "14:00", ShowTime.TO: "15:00"],
                        [Show.NAME: "Cinema updates", ShowTime.FROM: "15:00", ShowTime.TO: "16:00"],
                        [Show.NAME: "Evening upodates" , ShowTime.FROM: "16:00", ShowTime.TO: "17:00"],
                        [Show.NAME: "Global climate", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "18:00", ShowTime.TO: "19:00"],
                        [Show.NAME: "Hot news", ShowTime.FROM: "19:00", ShowTime.TO: "20:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "20:00", ShowTime.TO: "21:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "21:00", ShowTime.TO: "22:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "22:00", ShowTime.TO: "23:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "23:00", ShowTime.TO: "00:00"]]
    
    static let NEWS18 = [[Show.NAME: "Early morning news", ShowTime.FROM: "00:00", ShowTime.TO: "01:00"],
                        [Show.NAME: "Sports news", ShowTime.FROM: "01:00", ShowTime.TO: "02:00"],
                        [Show.NAME: "World politics", ShowTime.FROM: "02:00", ShowTime.TO: "03:00"],
                        [Show.NAME: "Wether prediction for globe", ShowTime.FROM: "03:00", ShowTime.TO: "04:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "04:00", ShowTime.TO: "05:00"],
                        [Show.NAME: "International updates", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "06:00", ShowTime.TO: "07:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "07:00", ShowTime.TO: "08:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "08:00", ShowTime.TO: "09:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "10:00", ShowTime.TO: "11:00"],
                        [Show.NAME: "Science to discuss", ShowTime.FROM: "11:00", ShowTime.TO: "12:00"],
                        [Show.NAME: "Animals around us", ShowTime.FROM: "12:00", ShowTime.TO: "13:00"],
                        [Show.NAME: "Water resources and management", ShowTime.FROM: "13:00", ShowTime.TO: "14:00"],
                        [Show.NAME: "Kollywood Box office", ShowTime.FROM: "14:00", ShowTime.TO: "15:00"],
                        [Show.NAME: "Cinema updates", ShowTime.FROM: "15:00", ShowTime.TO: "16:00"],
                        [Show.NAME: "Evening upodates" , ShowTime.FROM: "16:00", ShowTime.TO: "17:00"],
                        [Show.NAME: "Global climate", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "18:00", ShowTime.TO: "19:00"],
                        [Show.NAME: "Hot news", ShowTime.FROM: "19:00", ShowTime.TO: "20:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "20:00", ShowTime.TO: "21:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "21:00", ShowTime.TO: "22:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "22:00", ShowTime.TO: "23:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "23:00", ShowTime.TO: "00:00"]]

    static let MAALAIMURASU = [[Show.NAME: "Early morning news", ShowTime.FROM: "00:00", ShowTime.TO: "01:00"],
                        [Show.NAME: "Sports news", ShowTime.FROM: "01:00", ShowTime.TO: "02:00"],
                        [Show.NAME: "World politics", ShowTime.FROM: "02:00", ShowTime.TO: "03:00"],
                        [Show.NAME: "Wether prediction for globe", ShowTime.FROM: "03:00", ShowTime.TO: "04:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "04:00", ShowTime.TO: "05:00"],
                        [Show.NAME: "International updates", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "06:00", ShowTime.TO: "07:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "07:00", ShowTime.TO: "08:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "08:00", ShowTime.TO: "09:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "10:00", ShowTime.TO: "11:00"],
                        [Show.NAME: "Science to discuss", ShowTime.FROM: "11:00", ShowTime.TO: "12:00"],
                        [Show.NAME: "Animals around us", ShowTime.FROM: "12:00", ShowTime.TO: "13:00"],
                        [Show.NAME: "Water resources and management", ShowTime.FROM: "13:00", ShowTime.TO: "14:00"],
                        [Show.NAME: "Kollywood Box office", ShowTime.FROM: "14:00", ShowTime.TO: "15:00"],
                        [Show.NAME: "Cinema updates", ShowTime.FROM: "15:00", ShowTime.TO: "16:00"],
                        [Show.NAME: "Evening upodates" , ShowTime.FROM: "16:00", ShowTime.TO: "17:00"],
                        [Show.NAME: "Global climate", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "18:00", ShowTime.TO: "19:00"],
                        [Show.NAME: "Hot news", ShowTime.FROM: "19:00", ShowTime.TO: "20:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "20:00", ShowTime.TO: "21:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "21:00", ShowTime.TO: "22:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "22:00", ShowTime.TO: "23:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "23:00", ShowTime.TO: "00:00"]]
    
    static let SUNMUSIC = [[Show.NAME: "Early morning song", ShowTime.FROM: "00:00", ShowTime.TO: "02:00"],
                        [Show.NAME: "old songs", ShowTime.FROM: "02:00", ShowTime.TO: "02:30"],
                        [Show.NAME: "Classical hits", ShowTime.FROM: "02:30", ShowTime.TO: "03:30"],
                        [Show.NAME: "Classical kuthu", ShowTime.FROM: "03:30", ShowTime.TO: "04:30"],
                        [Show.NAME: "Devotional songs", ShowTime.FROM: "04:30", ShowTime.TO: "05:30"],
                        [Show.NAME: "Carnatic songs", ShowTime.FROM: "05:30", ShowTime.TO: "06:30"],
                        [Show.NAME: "Kacheri", ShowTime.FROM: "06:30", ShowTime.TO: "07:30"],
                        [Show.NAME: "Recent hits" , ShowTime.FROM: "07:30", ShowTime.TO: "08:30"],
                        [Show.NAME: "Non stop nonsense", ShowTime.FROM: "08:30", ShowTime.TO: "09:30"],
                        [Show.NAME: "Break free songs", ShowTime.FROM: "09:30", ShowTime.TO: "11:30"],
                        [Show.NAME: "Mix hits", ShowTime.FROM: "11:30", ShowTime.TO: "12:30"],
                        [Show.NAME: "Sound", ShowTime.FROM: "12:30", ShowTime.TO: "13:30"],
                        [Show.NAME: "Rahmania", ShowTime.FROM: "13:30", ShowTime.TO: "14:30"],
                        [Show.NAME: "Kollywood Hits", ShowTime.FROM: "14:30", ShowTime.TO: "15:30"],
                        [Show.NAME: "Melodies", ShowTime.FROM: "15:30", ShowTime.TO: "16:30"],
                        [Show.NAME: "Sad songs" , ShowTime.FROM: "16:30", ShowTime.TO: "17:30"],
                        [Show.NAME: "Ilayaraja songs", ShowTime.FROM: "17:30", ShowTime.TO: "18:30"],
                        [Show.NAME: "Jyothika hits", ShowTime.FROM: "18:30", ShowTime.TO: "19:30"],
                        [Show.NAME: "Rajini hits", ShowTime.FROM: "19:30", ShowTime.TO: "20:30"],
                        [Show.NAME: "Sivaji hits", ShowTime.FROM: "20:30", ShowTime.TO: "21:30"],
                        [Show.NAME: "Surya hits" , ShowTime.FROM: "21:30", ShowTime.TO: "22:30"],
                        [Show.NAME: "Vijay hits", ShowTime.FROM: "22:30", ShowTime.TO: "23:30"],
                        [Show.NAME: "SK hits", ShowTime.FROM: "23:30", ShowTime.TO: "00:00"]]
    
    static let VIJAYMUSIC = [[Show.NAME: "Early morning song", ShowTime.FROM: "00:00", ShowTime.TO: "02:00"],
                             [Show.NAME: "old songs", ShowTime.FROM: "02:00", ShowTime.TO: "02:30"],
                             [Show.NAME: "Classical hits", ShowTime.FROM: "02:30", ShowTime.TO: "03:30"],
                             [Show.NAME: "Classical kuthu", ShowTime.FROM: "03:30", ShowTime.TO: "04:30"],
                             [Show.NAME: "Devotional songs", ShowTime.FROM: "04:30", ShowTime.TO: "05:30"],
                             [Show.NAME: "Carnatic songs", ShowTime.FROM: "05:30", ShowTime.TO: "06:30"],
                             [Show.NAME: "Kacheri", ShowTime.FROM: "06:30", ShowTime.TO: "07:30"],
                             [Show.NAME: "Recent hits" , ShowTime.FROM: "07:30", ShowTime.TO: "08:30"],
                             [Show.NAME: "Non stop nonsense", ShowTime.FROM: "08:30", ShowTime.TO: "09:30"],
                             [Show.NAME: "Break free songs", ShowTime.FROM: "09:30", ShowTime.TO: "11:30"],
                             [Show.NAME: "Mix hits", ShowTime.FROM: "11:30", ShowTime.TO: "12:30"],
                             [Show.NAME: "Sound", ShowTime.FROM: "12:30", ShowTime.TO: "13:30"],
                             [Show.NAME: "Rahmania", ShowTime.FROM: "13:30", ShowTime.TO: "14:30"],
                             [Show.NAME: "Kollywood Hits", ShowTime.FROM: "14:30", ShowTime.TO: "15:30"],
                             [Show.NAME: "Melodies", ShowTime.FROM: "15:30", ShowTime.TO: "16:30"],
                             [Show.NAME: "Sad songs" , ShowTime.FROM: "16:30", ShowTime.TO: "17:30"],
                             [Show.NAME: "Ilayaraja songs", ShowTime.FROM: "17:30", ShowTime.TO: "18:30"],
                             [Show.NAME: "Jyothika hits", ShowTime.FROM: "18:30", ShowTime.TO: "19:30"],
                             [Show.NAME: "Rajini hits", ShowTime.FROM: "19:30", ShowTime.TO: "20:30"],
                             [Show.NAME: "Sivaji hits", ShowTime.FROM: "20:30", ShowTime.TO: "21:30"],
                             [Show.NAME: "Surya hits" , ShowTime.FROM: "21:30", ShowTime.TO: "22:30"],
                             [Show.NAME: "Vijay hits", ShowTime.FROM: "22:30", ShowTime.TO: "23:30"],
                             [Show.NAME: "SK hits", ShowTime.FROM: "23:30", ShowTime.TO: "00:00"]]
    
    static let RAJMUSIC = [[Show.NAME: "Early morning song", ShowTime.FROM: "00:00", ShowTime.TO: "02:00"],
                           [Show.NAME: "old songs", ShowTime.FROM: "02:00", ShowTime.TO: "02:30"],
                           [Show.NAME: "Classical hits", ShowTime.FROM: "02:30", ShowTime.TO: "03:30"],
                           [Show.NAME: "Classical kuthu", ShowTime.FROM: "03:30", ShowTime.TO: "04:30"],
                           [Show.NAME: "Devotional songs", ShowTime.FROM: "04:30", ShowTime.TO: "05:30"],
                           [Show.NAME: "Carnatic songs", ShowTime.FROM: "05:30", ShowTime.TO: "06:30"],
                           [Show.NAME: "Kacheri", ShowTime.FROM: "06:30", ShowTime.TO: "07:30"],
                           [Show.NAME: "Recent hits" , ShowTime.FROM: "07:30", ShowTime.TO: "08:30"],
                           [Show.NAME: "Non stop nonsense", ShowTime.FROM: "08:30", ShowTime.TO: "09:30"],
                           [Show.NAME: "Break free songs", ShowTime.FROM: "09:30", ShowTime.TO: "11:30"],
                           [Show.NAME: "Mix hits", ShowTime.FROM: "11:30", ShowTime.TO: "12:30"],
                           [Show.NAME: "Sound", ShowTime.FROM: "12:30", ShowTime.TO: "13:30"],
                           [Show.NAME: "Rahmania", ShowTime.FROM: "13:30", ShowTime.TO: "14:30"],
                           [Show.NAME: "Kollywood Hits", ShowTime.FROM: "14:30", ShowTime.TO: "15:30"],
                           [Show.NAME: "Melodies", ShowTime.FROM: "15:30", ShowTime.TO: "16:30"],
                           [Show.NAME: "Sad songs" , ShowTime.FROM: "16:30", ShowTime.TO: "17:30"],
                           [Show.NAME: "Ilayaraja songs", ShowTime.FROM: "17:30", ShowTime.TO: "18:30"],
                           [Show.NAME: "Jyothika hits", ShowTime.FROM: "18:30", ShowTime.TO: "19:30"],
                           [Show.NAME: "Rajini hits", ShowTime.FROM: "19:30", ShowTime.TO: "20:30"],
                           [Show.NAME: "Sivaji hits", ShowTime.FROM: "20:30", ShowTime.TO: "21:30"],
                           [Show.NAME: "Surya hits" , ShowTime.FROM: "21:30", ShowTime.TO: "22:30"],
                           [Show.NAME: "Vijay hits", ShowTime.FROM: "22:30", ShowTime.TO: "23:30"],
                           [Show.NAME: "SK hits", ShowTime.FROM: "23:30", ShowTime.TO: "00:00"]]

    static let JAYAMAX = [[Show.NAME: "Early morning song", ShowTime.FROM: "00:00", ShowTime.TO: "02:00"],
                          [Show.NAME: "old songs", ShowTime.FROM: "02:00", ShowTime.TO: "02:30"],
                          [Show.NAME: "Classical hits", ShowTime.FROM: "02:30", ShowTime.TO: "03:30"],
                          [Show.NAME: "Classical kuthu", ShowTime.FROM: "03:30", ShowTime.TO: "04:30"],
                          [Show.NAME: "Devotional songs", ShowTime.FROM: "04:30", ShowTime.TO: "05:30"],
                          [Show.NAME: "Carnatic songs", ShowTime.FROM: "05:30", ShowTime.TO: "06:30"],
                          [Show.NAME: "Kacheri", ShowTime.FROM: "06:30", ShowTime.TO: "07:30"],
                          [Show.NAME: "Recent hits" , ShowTime.FROM: "07:30", ShowTime.TO: "08:30"],
                          [Show.NAME: "Non stop nonsense", ShowTime.FROM: "08:30", ShowTime.TO: "09:30"],
                          [Show.NAME: "Break free songs", ShowTime.FROM: "09:30", ShowTime.TO: "11:30"],
                          [Show.NAME: "Mix hits", ShowTime.FROM: "11:30", ShowTime.TO: "12:30"],
                          [Show.NAME: "Sound", ShowTime.FROM: "12:30", ShowTime.TO: "13:30"],
                          [Show.NAME: "Rahmania", ShowTime.FROM: "13:30", ShowTime.TO: "14:30"],
                          [Show.NAME: "Kollywood Hits", ShowTime.FROM: "14:30", ShowTime.TO: "15:30"],
                          [Show.NAME: "Melodies", ShowTime.FROM: "15:30", ShowTime.TO: "16:30"],
                          [Show.NAME: "Sad songs" , ShowTime.FROM: "16:30", ShowTime.TO: "17:30"],
                          [Show.NAME: "Ilayaraja songs", ShowTime.FROM: "17:30", ShowTime.TO: "18:30"],
                          [Show.NAME: "Jyothika hits", ShowTime.FROM: "18:30", ShowTime.TO: "19:30"],
                          [Show.NAME: "Rajini hits", ShowTime.FROM: "19:30", ShowTime.TO: "20:30"],
                          [Show.NAME: "Sivaji hits", ShowTime.FROM: "20:30", ShowTime.TO: "21:30"],
                          [Show.NAME: "Surya hits" , ShowTime.FROM: "21:30", ShowTime.TO: "22:30"],
                          [Show.NAME: "Vijay hits", ShowTime.FROM: "22:30", ShowTime.TO: "23:30"],
                          [Show.NAME: "SK hits", ShowTime.FROM: "23:30", ShowTime.TO: "00:00"]]
    
    static let SUNMOVIES = [[Show.NAME: "movie 1", ShowTime.FROM: "00:00", ShowTime.TO: "03:00"],
                            [Show.NAME: "movie 2", ShowTime.FROM: "03:00", ShowTime.TO: "06:00"],
                            [Show.NAME: "movie 3", ShowTime.FROM: "06:00", ShowTime.TO: "09:00"],
                            [Show.NAME: "movie 4", ShowTime.FROM: "09:00", ShowTime.TO: "12:00"],
                            [Show.NAME: "movie 5", ShowTime.FROM: "12:00", ShowTime.TO: "15:00"],
                            [Show.NAME: "movie 6", ShowTime.FROM: "15:00", ShowTime.TO: "18:00"],
                            [Show.NAME: "movie 7", ShowTime.FROM: "18:00", ShowTime.TO: "21:00"],
                            [Show.NAME: "movie 8", ShowTime.FROM: "21:00", ShowTime.TO: "00:00"]]

    static let VIJAYSUPER = [[Show.NAME: "movie 1", ShowTime.FROM: "00:00", ShowTime.TO: "03:00"],
                             [Show.NAME: "movie 2", ShowTime.FROM: "03:00", ShowTime.TO: "06:00"],
                             [Show.NAME: "movie 3", ShowTime.FROM: "06:00", ShowTime.TO: "09:00"],
                             [Show.NAME: "movie 4", ShowTime.FROM: "09:00", ShowTime.TO: "12:00"],
                             [Show.NAME: "movie 5", ShowTime.FROM: "12:00", ShowTime.TO: "15:00"],
                             [Show.NAME: "movie 6", ShowTime.FROM: "15:00", ShowTime.TO: "18:00"],
                             [Show.NAME: "movie 7", ShowTime.FROM: "18:00", ShowTime.TO: "21:00"],
                             [Show.NAME: "movie 8", ShowTime.FROM: "21:00", ShowTime.TO: "00:00"]]
    
    static let ZEETHIRAI = [[Show.NAME: "movie 1", ShowTime.FROM: "00:00", ShowTime.TO: "03:00"],
                            [Show.NAME: "movie 2", ShowTime.FROM: "03:00", ShowTime.TO: "06:00"],
                            [Show.NAME: "movie 3", ShowTime.FROM: "06:00", ShowTime.TO: "09:00"],
                            [Show.NAME: "movie 4", ShowTime.FROM: "09:00", ShowTime.TO: "12:00"],
                            [Show.NAME: "movie 5", ShowTime.FROM: "12:00", ShowTime.TO: "15:00"],
                            [Show.NAME: "movie 6", ShowTime.FROM: "15:00", ShowTime.TO: "18:00"],
                            [Show.NAME: "movie 7", ShowTime.FROM: "18:00", ShowTime.TO: "21:00"],
                            [Show.NAME: "movie 8", ShowTime.FROM: "21:00", ShowTime.TO: "00:00"]]

    static let RAJNEWS = [[Show.NAME: "Early morning news", ShowTime.FROM: "00:00", ShowTime.TO: "01:00"],
                        [Show.NAME: "Sports news", ShowTime.FROM: "01:00", ShowTime.TO: "02:00"],
                        [Show.NAME: "World politics", ShowTime.FROM: "02:00", ShowTime.TO: "03:00"],
                        [Show.NAME: "Wether prediction for globe", ShowTime.FROM: "03:00", ShowTime.TO: "04:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "04:00", ShowTime.TO: "05:00"],
                        [Show.NAME: "International updates", ShowTime.FROM: "05:00", ShowTime.TO: "06:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "06:00", ShowTime.TO: "07:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "07:00", ShowTime.TO: "08:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "08:00", ShowTime.TO: "09:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "10:00", ShowTime.TO: "11:00"],
                        [Show.NAME: "Science to discuss", ShowTime.FROM: "11:00", ShowTime.TO: "12:00"],
                        [Show.NAME: "Animals around us", ShowTime.FROM: "12:00", ShowTime.TO: "13:00"],
                        [Show.NAME: "Water resources and management", ShowTime.FROM: "13:00", ShowTime.TO: "14:00"],
                        [Show.NAME: "Kollywood Box office", ShowTime.FROM: "14:00", ShowTime.TO: "15:00"],
                        [Show.NAME: "Cinema updates", ShowTime.FROM: "15:00", ShowTime.TO: "16:00"],
                        [Show.NAME: "Evening upodates" , ShowTime.FROM: "16:00", ShowTime.TO: "17:00"],
                        [Show.NAME: "Global climate", ShowTime.FROM: "17:00", ShowTime.TO: "18:00"],
                        [Show.NAME: "Breaking news", ShowTime.FROM: "18:00", ShowTime.TO: "19:00"],
                        [Show.NAME: "Hot news", ShowTime.FROM: "19:00", ShowTime.TO: "20:00"],
                        [Show.NAME: "Local news", ShowTime.FROM: "20:00", ShowTime.TO: "21:00"],
                        [Show.NAME: "Election upodates" , ShowTime.FROM: "21:00", ShowTime.TO: "22:00"],
                        [Show.NAME: "Central news", ShowTime.FROM: "22:00", ShowTime.TO: "23:00"],
                        [Show.NAME: "State news", ShowTime.FROM: "23:00", ShowTime.TO: "00:00"]]


}
